<?php
/**
 * @file
 * This module directs outbound email to the Elastic Email service.
 * To use this service, you need an Elastic Email account so you can provide a
 * username and API key to this module.
 *
 * This module allows for the inclusion of ElasticEmail as the native Drupal mail
 * handler using the new Drupal mail system interface.
 *
 * @see http://elasticemail.com
 */

/**
 * Implements hook_menu().
 */
function elastic_email_menu() {
  $items = array();

  $items['admin/config/system/elastic_email'] = array(
    'title' => 'Elastic Email',
    'description' => 'Configure Elastic Email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elastic_email_settings_form'),
    'file' => 'elastic_email.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'));

  $items['admin/config/system/elastic_email/test'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'elastic_email_test_config',
    'file' => 'elastic_email.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'));

  return $items;
}

/**
 * Implements hook_help().
 */
function elastic_email_help($path = '', $arg = '') {

  switch ($path) {
    case 'admin/help#elastic_email':
      // Return the README inside a <pre> element.
      $help = file_get_contents(dirname(__FILE__) . "/README.txt");
      return '<pre>' . $help . '</pre>';

    case 'admin/settings/elastic_email':
      // Introductory text.
      $help = '<p>'
        . t('Elastic Email is a (commercial) mail relay service. It is particularly
          of use as a mail relay for cloud-hosted (e.g. Amazon EC2) websites that
          may be subject to IP-based spam filtering, or sites that have restrictions
          on outbound ports.')
        . '</p><p>'
        . t('This module intercepts outgoing Drupal mail, and delivers it to the
          Elastic Email REST-style service over HTTPS. Note that email is delivered
          as though all recipients are BCC (that is, recipients cannot see other
          recipients of the message).')
        . '</p><p>'
        . t('To use the service, visit the <a href="http://elasticemail.com">Elastic
          Email website</a> and sign-up to get an account <em>username</em> and
          <em>API Key</em>.')
        . '</p>';
      return $help;
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function elastic_email_cron_queue_info() {
  $queues = array();
  $queues['elastic_email'] = array(
    'worker callback' => 'elastic_email_cron_send',
    'time' => 5,
  );
  return $queues;
}

/**
 * Sends the emails that are in the queue.
 *
 * @param $message
 *   The email message string that will be sent.
 */
function elastic_email_cron_send($message) {
  module_load_include('inc', 'elastic_email', 'mail');
  ElasticEmailMailSystem::cronSend($message);
}
