elastic_email.settings:
  type: mapping
  label: Settings
  mapping:
    username:
      type: string
    api_key:
      type: string
    queue_enabled:
      type: boolean
    log_success:
      type: boolean
    credit_low_threshold:
      type: integer
    use_default_channel:
      type: boolean
    default_channel:
      type: string

